name: flutter_boilerplate_hng11
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  dio: ^5.5.0+1
  google_sign_in: ^6.2.1
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  flutter_dotenv: ^5.1.0
  one_context: ^4.0.0
  get_storage: ^2.1.1
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.10+1
  back_button_interceptor: ^7.0.3
  file_picker: ^8.1.1
  vector_graphics: any
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  freezed_annotation: ^2.4.4
  syncfusion_flutter_charts:
  riverpod_annotation: ^2.3.5
  flutter_shimmer: ^2.1.2
  json_annotation: any
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

  http_parser: ^4.0.2
  # flutter_inappwebview: ^5.8.0
  badges: ^3.1.2
  share_plus: ^10.0.2
  jiffy: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  # flutter_gen: ^5.6.0
  # flutter_gen_runner:  
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  generate: true

  uses-material-design: true
  fonts:
    - family: NavBar
      fonts:
        - asset: assets/icons/bottom_bar/NavBar.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/png/
    - assets/images/png/product_listing/
    - assets/images/svg/product_listing/
    - assets/images/svg/account_settings/
    - assets/images/svg/
    - assets/icons/

    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  integrations:
    flutter_localizations: true
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
