name: QA workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up the Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.3
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get
      
      - name: Running analysis on project
        run: flutter analyze
      
      - name: Building apk
        run: flutter build apk
